version: '3.1'

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 6156_project
    ports:
      - "27017:27017"

  app:
    build: ./app
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
