name: CI/CD Pipeline
# Using Github Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Copy files to EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: 54.167.236.204
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        source: "."
        target: "~/dockers"
    
    - name: Deploy on EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: 54.167.236.204
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/dockers
          docker-compose down
          docker-compose build
          docker-compose up -d
