name: CI/CD Pipeline
# Using Github Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image
      run: |
        docker-compose build
    
    - name: Login to Docker Registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
    - name: Push Docker image
      run: |
        docker-compose push

    - name: Copy files to EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: 54.167.236.204
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        source: "."
        target: "~/dockers"
    
    - name: Deploy on EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: 54.167.236.204
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/dockers
          docker-compose down
          docker-compose pull
          docker-compose up -d

    # - name: Set up ssh key
    #   run: |
    #     echo "${{ secrets.EC2_KEY }}" > my_private_key.pem
    #     chmod 600 my_private_key.pem

    # - name: Build Docker Image
    #   run: |
    #     # docker build -t your-app-name .
    #     echo "Build Docker Image"

    # - name: Deploy to AWS EC2
    #   run: |
    #     ssh -i my_private_key.pem -o "StrictHostKeyChecking=no" ec2-user@54.167.236.204 && cd /home/ec2-user/billing-microservice && docker-compose up --build
    #     echo "Deploying the app to EC2"
